.. faq:

FAQs
====

Below is a list of commonly encountered issues and accompanying solutions:

.. topic:: I get a :code:`FileNotFound` error when I try to load data from a datastore
   
   This is usually because you didn't include the storage flags for these data when you started your JupyterLab session. Please make sure that you're a member of the projects that house the data you want to access (see :ref:`prerequisites`) and that you've set your storage flags correctly (see :ref:`are_setup`).

.. note::
   Need help? Please open an issue `here <https://github.com/ACCESS-NRI/access-nri-intake-catalog/issues>`_.